### ISSUE TITLE
spec v2.0 and configuration file

### ISSUE THREAD

**Issue by noraj** [porras/tlcr#14]
I just wanted to say that the [v2.0 of the spec is out](https://github.com/tldr-pages/tldr/releases/tag/v2.0) and that I relaunched the discussion about having a [standardized configuration file](https://github.com/tldr-pages/tldr/issues/876) across all clients (and platforms).

**Comment by porras** [comment]
Hi! thanks for the heads up. As it's almost obvious, this project is abandoned and I'm going to make that explicit and close all issues and archiving the repo. It was a nice learning experience back then, but there's currently no reason for this client to exist, the official one is so much better. Thank you!
