### ISSUE TITLE
Unexpected end of HTTP response

### ISSUE THREAD

**Issue by porras** [porras/tlcr#6]
```
#~> tlcr cd
Fetching index...
unexpected end of http response (Exception)
[4482230683] *raise<String>:NoReturn +139
[4482293217] *HTTP::Client#exec<HTTP::Client, String, String, Nil, Nil>:HTTP::Response +8385
[4482269455] *Tlcr::Client#index<Tlcr::Client>:Tlcr::Index +1519
[4482211524] __crystal_main +23748
[4482253963] main +43
```

(originally reported by @sfcgeorge in #4)

**Comment by sfcgeorge** [comment]
I'm not sure what else to say, sorry. Whatever I do I get that error and my internet seems to be working fine. I tried disabling OS X firewall but that wasn't it. Let me know if there are any logs or versions of things you'd like me to share. 

I'm on OS X 10.11 with Crystal 0.10.0, installed via Homebrew.

**Comment by porras** [comment]
Thanks for reporting, I'll give it a deeper look. The only difference with my own environment is that I'm on OS X 10.10, but I've had reports of it working on 10.11. Today or tomorrow I'll push a binary for 10.11 (the only one available so far is the one I built in my environment, for 10.10), it'd be nice if you could try it. Thanks!
